name: Jekyll site CI

on:
  push:
    branches: [ "obsidian" ]
  pull_request:
    branches: [ "obsidian" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.2'  # 您可以根据项目需求选择合适的 Ruby 版本

      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.3
          bundle install

      - name: Build Jekyll site
        run: bundle exec jekyll build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.HUNTERZJU }}
          publish_dir: _site

